次のコードは、何がまずいでしょう。

public static void main(String[] args){
    ex1();
}

public static void ex1(){
    ex2();
}

public static void ex2() throws Exception{
    throw new Exception();
}

//ex2の呼び出し元で例外処理が行われていないのでコンパイルエラー。