try-catchブロックを使用した例外処理について、正しい記述はどれですか。

catchブロック内で例外が発生する可能性のある処理を囲む。
//誤り。catchブロック内では例外発生時の実行分を記述する。

tryブロック内で例外処理を定義できる。
//誤り。tryブロック内では例外が発生する可能性のある、通常実行する文を記述する。

finallyブロックの定義は任意である。
//正しい。

catchブロックは一つしか使うことができない。
//誤り。複数のcatchブロックを設定し複数の例外処理を実行可能。